input_dir: "datasets/new_angle/"
output_dir: "new_angle"

max_keypoints: 6000  

geometry_type: "Homography"
ransac_method: "CV2_USAC_MAGSAC"
ransac_reproj_threshold: 13.0  
ransac_max_iter: 50000
ransac_confidence: 0.9999
debug_mode: true

save_essential: "all"  # all, 2d, 3d, none

depth_max: 4000.0

enable_3d_matching: true

stable_depth_range: 50.0 # +-50.0mm

pose_estimation_method: "ransac"  # "svd" 또는 "ransac"

result_image_contrast: 5.0
# 3D RANSAC 파라미터
ransac_3d:
  max_correspondence_distance: 0.2
  ransac_n: 7                         
  max_iterations: 3000                
  confidence: 0.9999
              

image_size:
  width: 1224
  height: 1024

